"""
MCP code generation engine.
Takes a normalized analysis result and generates an MCP server
using Jinja2 templates per target language.
Also runs an LLM "polish pass" to improve quality.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, select_autoescape

from config import get_settings
from db.models import AnalysisResult, TargetLanguage

TEMPLATES_DIR = Path(__file__).parent / "templates"


class GeneratorEngine:
    """
    Given an AnalysisResult, produce a dict of {filename: content}
    representing a complete MCP server project.
    """

    def __init__(
        self,
        analysis: dict,
        project_name: str,
        target_language: TargetLanguage = TargetLanguage.PYTHON_FASTMCP,
        auth_config: dict | None = None,
        source_files: dict[str, str] | None = None,
        clarifications: list[dict] | None = None,
    ):
        self._analysis = analysis
        self._project_name = project_name
        self._target = target_language
        self._auth = auth_config or {}
        self._source_files = source_files or {}
        self._clarifications: list[dict] = clarifications or []
        self._env = Environment(
            loader=FileSystemLoader(str(TEMPLATES_DIR)),
            autoescape=select_autoescape([]),
            trim_blocks=True,
            lstrip_blocks=True,
        )

    async def generate(self) -> dict[str, str]:
        """Return dict of {filename: content}."""
        context = self._build_context()
        template_dir = self._get_template_dir()
        files: dict[str, str] = {}

        # Render all .j2 templates in the target dir
        for tmpl_path in TEMPLATES_DIR.glob(f"{template_dir}/**/*.j2"):
            rel = tmpl_path.relative_to(TEMPLATES_DIR / template_dir)
            out_name = str(rel).removesuffix(".j2")
            template = self._env.get_template(f"{template_dir}/{rel}")
            rendered = template.render(**context)
            files[out_name] = rendered

        # Rename the template server file to match the source entrypoint filename
        entrypoint = self._detect_entrypoint()
        template_server = next(
            (k for k in files if k in ("server.py", "server.js", "main.go")), None
        )
        if entrypoint and template_server and entrypoint != template_server:
            files[entrypoint] = files.pop(template_server)

        # LLM polish pass — let the LLM review and improve the generated code
        if files:
            files = await self._polish_pass(files, context)

        # Inject non-entrypoint source files verbatim (models, schemas, db, etc.)
        # These are support files that don't need MCP conversion but are needed at runtime
        if self._source_files:
            mcp_files = set(files.keys())
            effective_entrypoint = entrypoint or template_server
            for fname, content in self._source_files.items():
                # Skip: already generated by template, or the entrypoint (MCP version replaces it)
                if fname in mcp_files or fname == effective_entrypoint:
                    continue
                # Skip test files and non-code files we don't want to carry over
                if fname.startswith("test_") or fname.endswith(("_test.py", ".pyc", ".lock")):
                    continue
                files[fname] = content

        return files

    def _detect_entrypoint(self) -> str | None:
        """Detect the primary entrypoint filename from source files."""
        if not self._source_files:
            return None
        # Priority order — most common entrypoint names first
        for candidate in ["main.py", "app.py", "server.py", "api.py", "index.py",
                           "main.js", "app.js", "server.js", "index.js",
                           "main.go"]:
            if candidate in self._source_files:
                return candidate
        # Fallback: first source file with a known code extension
        for fname in self._source_files:
            if fname.endswith((".py", ".js", ".go")):
                return fname
        return None

    def _build_context(self) -> dict:
        """Build Jinja2 template context from analysis data."""
        endpoints = self._analysis.get("endpoints", [])
        # Normalize all endpoints to template-expected field names
        endpoints = [self._normalize_endpoint(e) for e in endpoints]
        tools      = [e for e in endpoints if e.get("mcp_type") in ("tool", None)]
        resources  = [e for e in endpoints if e.get("mcp_type") == "resource"]
        prompts    = [e for e in endpoints if e.get("mcp_type") == "prompt"]

        return {
            "project_name": self._project_name,
            "project_slug": re.sub(r"[^a-z0-9_]", "_", self._project_name.lower()),
            "base_url": self._analysis.get("base_url", ""),
            "language": self._analysis.get("language", "unknown"),
            "framework": self._analysis.get("framework", "unknown"),
            "auth_info": self._analysis.get("auth_info", {}),
            "auth_config": self._auth,
            "schemas": self._analysis.get("schemas", {}),
            "endpoints": endpoints,
            "tools": tools,
            "resources": resources,
            "prompts": prompts,
            "notes": self._analysis.get("notes", ""),
            "clarifications": self._clarifications,
        }

    @staticmethod
    def _normalize_endpoint(ep: dict) -> dict:
        """
        Ensure every endpoint has the template-expected fields:
        operation_id, summary, path_params, query_params, body_schema.
        Handles both OpenAPI-analyzer output (already correct) and
        LLM-analyzer output which uses 'name' + flat 'parameters' list.
        """
        # OpenAPI analyzer / static extractor already produce these fields — fast path
        if ep.get("operation_id") and ep.get("path_params") is not None:
            return ep

        path = ep.get("path", ep.get("name", "/"))
        method = ep.get("method", "GET").upper()
        path_param_names = set(re.findall(r"\{(\w+)\}", path))
        all_params = ep.get("parameters", [])

        path_params = [p for p in all_params if p.get("name") in path_param_names]
        remaining   = [p for p in all_params if p.get("name") not in path_param_names]

        query_params: list[dict] = []
        has_body = False
        for p in remaining:
            ptype = p.get("type", "").lower()
            pname = p.get("name", "")
            if method in ("POST", "PUT", "PATCH"):
                if ptype in ("object", "dict") or pname.lower() in ("body", "payload", "data"):
                    has_body = True
                # else: skip body fields from query params
            else:
                query_params.append(p)

        # If POST/PUT/PATCH has non-path params but none recognised as body, assume body
        if method in ("POST", "PUT", "PATCH") and remaining and not has_body:
            has_body = True

        return {
            **ep,
            "operation_id": ep.get("operation_id") or ep.get("name", "unnamed"),
            "summary": ep.get("summary") or ep.get("description", ""),
            "path_params": path_params,
            "query_params": query_params,
            "body_schema": ep.get("body_schema") if "body_schema" in ep else ({"type": "object"} if has_body else None),
        }

    def _get_template_dir(self) -> str:
        mapping = {
            TargetLanguage.PYTHON_FASTMCP: "python_fastmcp",
            TargetLanguage.NODEJS:         "nodejs",
            TargetLanguage.GO:             "go",
            TargetLanguage.GENERIC:        "python_fastmcp",  # fallback
        }
        return mapping.get(self._target, "python_fastmcp")

    async def _polish_pass(self, files: dict[str, str], context: dict) -> dict[str, str]:
        """Ask the LLM to review and improve the main server file."""
        # Prefer the detected entrypoint; fall back to any file with a server/main/index name
        entrypoint = self._detect_entrypoint()
        main_file = (
            entrypoint if entrypoint and entrypoint in files
            else next((k for k in files if "server" in k or "main" in k or "index" in k), None)
        )
        if not main_file:
            return files

        code = files[main_file]
        clarification_block = ""
        if self._clarifications:
            lines = ["USER DECISIONS (apply these exactly):"]
            for c in self._clarifications:
                lines.append(f"  Q: {c['question']}")
                lines.append(f"  A: {c['answer']}")
            clarification_block = "\n".join(lines) + "\n\n"

        prompt = f"""You are an expert MCP (Model Context Protocol) developer.
Review this auto-generated MCP server code and improve it:
- Fix any syntax errors
- Improve parameter type hints
- Improve tool/resource descriptions to be clear for LLM agents
- Add proper error handling
- Ensure async/await is used correctly
- Keep all the endpoints — do not remove any
{clarification_block}
Return ONLY the improved code, no explanation.

PROJECT: {context['project_name']}
BASE URL: {context['base_url']}

CODE:
{code}
"""
        try:
            improved = await self._call_llm(prompt)
            # 1. Strip thinking blocks (Gemini 2.5 "<think>" wrapper)
            improved = re.sub(r"<think>.*?</think>", "", improved, flags=re.DOTALL).strip()
            # 2. Extract from code fence - handles responses wrapped in docstrings or extra text
            fence_match = re.search(r"```(?:python)?\n(.*?)```", improved, re.DOTALL)
            if fence_match:
                improved = fence_match.group(1).strip()
            else:
                # Strip any leading / trailing fence that wasn't paired
                improved = re.sub(r"^```\w*\n?", "", improved.strip())
                improved = re.sub(r"\n?```$", "", improved.strip()).strip()
            # 3. Validate — if LLM dropped all MCP decorators, keep the template output
            from core.generator.validator import MCPValidator
            if MCPValidator().validate_python(improved).valid:
                files[main_file] = improved
            # else: improved is broken — silently keep original template output
        except Exception:
            pass  # Keep original if polish fails

        return files

    async def _call_llm(self, prompt: str) -> str:
        settings = get_settings()
        provider = settings.llm_provider
        if provider == "gemini":
            import asyncio
            from google import genai
            client = genai.Client(api_key=settings.gemini_api_key)
            resp = await asyncio.to_thread(
                client.models.generate_content,
                model=settings.gemini_model,
                contents=prompt,
            )
            return resp.text
        elif provider == "anthropic":
            import anthropic
            client = anthropic.AsyncAnthropic(api_key=settings.anthropic_api_key)
            msg = await client.messages.create(
                model=settings.anthropic_model,
                max_tokens=8192,
                messages=[{"role": "user", "content": prompt}],
            )
            return msg.content[0].text
        elif provider == "local":
            from core.llm.local_provider import generate
            return await generate(prompt, max_new_tokens=8192)
        else:
            from openai import AsyncOpenAI
            client = AsyncOpenAI(api_key=settings.openai_api_key)
            resp = await client.chat.completions.create(
                model=settings.openai_model,
                messages=[{"role": "user", "content": prompt}],
            )
            return resp.choices[0].message.content
